BEGIN;

CREATE TABLE EDITORA (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(255)
);

CREATE TABLE LIVRO (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	ID_EDITORA INTEGER REFERENCES EDITORA(ID),
	QUANTIDADE_TOTAL INTEGER NOT NULL,
	QUANTIDADE_DISPONIVEL INTEGER NOT NULL
);

CREATE TABLE EDICOES (
	ID SERIAL PRIMARY KEY,
	ID_LIVRO INTEGER REFERENCES LIVRO(ID),
	NOME_EDICAO VARCHAR(50) NOT NULL,
	DATA_LANCAMENTO DATE NOT NULL,
	QUANTIDADE INTEGER NOT NULL,
	UNIQUE (ID_LIVRO, NOME_EDICAO)
);

CREATE TABLE NACIONALIDADE (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL
);

CREATE TABLE AUTOR (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	ID_NACIONALIDADE INTEGER REFERENCES NACIONALIDADE(ID)
);

CREATE TABLE USUARIO (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) UNIQUE NOT NULL,
	TELEFONE VARCHAR(20),
	ENDERECO VARCHAR(255)
);

CREATE TABLE EMPRESTIMO (
	ID SERIAL PRIMARY KEY,
	ID_USUARIO INTEGER REFERENCES USUARIO(ID),
	DATA_EMPRESTIMO DATE NOT NULL,
	DATA_DEVOLUCAO_PREVISTA DATE,
	DATA_DEVOLUCAO_REAL DATE
);

CREATE TABLE EMPRESTIMO_LIVRO (
	ID_EMPRESTIMO INTEGER REFERENCES EMPRESTIMO(ID) ON DELETE CASCADE,
	ID_LIVRO INTEGER REFERENCES LIVRO(ID) ON DELETE CASCADE,
	ID_EDICAO INTEGER REFERENCES EDICOES(ID) ON DELETE CASCADE,
	PRIMARY KEY (ID_EMPRESTIMO, ID_LIVRO, ID_EDICAO)
);

CREATE TABLE LIVRO_AUTOR (
	ID_LIVRO INTEGER REFERENCES LIVRO(ID),
	ID_AUTOR INTEGER REFERENCES AUTOR(ID),
	PRIMARY KEY (ID_LIVRO, ID_AUTOR)
);

COMMIT;