version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./01_library.sql:/docker-entrypoint-initdb.d/01_library.sql
#      - ./02_library.sql:/docker-entrypoint-initdb.d/02_library.sql
      - ./03_library.sql:/docker-entrypoint-initdb.d/03_library.sql

#volumes:
#  postgres_data:
#    driver: local

# DB URL
# jdbc:postgresql://localhost:5432/mydatabase